<!--
@author linbin
@content  the index page
-->
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>高校教师绩效考核系统</title>
<meta name="keywords" content="高校教师绩效考核系统" />
<meta name="description" content="高校教师绩效考核系统" />
<link rel="shortcut icon" href="./image/favicon.ico" />
<link rel="stylesheet" href="./css/style.css" />
<link rel="stylesheet" href="./css/main.css" />
<!-- jquery ui-->
<link rel="stylesheet" href="./css/jquery-ui.css" />
<script type="text/javascript" src="./js/Core.class.js"></script>
<script type="text/javascript" src="./js/SandBox.class.js"></script>
</head>
<body>
	<!-- the background-->
	<div class="logpdiv">
		<div id="background"
			style="position: absolute; width: 100%; height: 100%">
			<img style="width: 100%; height: auto;" alt="background" />
		</div>
	</div>

	<!-- the header element-->
	<header>
		<div id="logo" class="logo">
			<ul id="nav" style="float: left; color: white;" class="pre">
				  <?php
						
$navs = $this->navigation;
						for($i = 0; $i < count ( $navs ); $i ++) {
							$nav = $navs [$i];
							?>
							<li><a style="color: white;" href="<?php echo $nav['url']; ?>"><?php echo $nav['title']; ?></a>
				</li>
				  <?php }?>
				</ul>
			<input type="text" name="search" value="搜索" />
			<div>
					欢迎您：<?php echo $this->user['name']; ?>老师 
				</div>
		</div>
	</header>
	<div class="tran" style="height: 80px;"></div>
	<!-- the content element it contains by three parts-->
	<div id="Content" class="middle">
		<!-- the content part-->
		<div class="contain3" id="page_data">
			<div class="contain2">
				<div class="contain1" id="indexmain">
					<div id="left">
						<!-- 头像部分-->
						<div class="top" style="float: left;">
							    <?php if($this->user['avater'] === '暂无'){ ?>
								  <img src="./image/default.jpg" alt="defaultImage" />
								<?php } else { ?>
								  <img
								src="main/image?path=<?php echo $this->user['avater']; ?>"
								alt="defaultImage" />
								<?php }?>
								<div class="nick">
									<?php echo $this->user['nickname'];?>
								</div>
							<div class="clear"></div>
							<div class="sit">
								<a href="main/message">编辑资料</a>
							</div>
						</div>
						<div class="clear"></div>
						<div id="scroll" class="dis">
							<div class="clear">
								<a class="toTop" href="#top">Totop</a>
							</div>
							<div class="bottom" id="reel">
								<div class="info">
									<h2>详细信息:</h2>
									<h4>学院：<?php echo $this->user['college'];?></h4>
									<h4>姓名：<?php echo $this->user['name'];?></h3>
										<h4>职位：<?php echo $this->user['post'];?></h4>
										<h4>主修专业：<?php echo $this->user['specialty'];?></h4>
										<h4>教学课程：<?php echo $this->user['tutorial'];?></h4>
										<h4>办公室地址：<?php echo $this->user['office'];?></h4>
										<h4>联系方式：<?php echo $this->user['contact'];?></h4>
								
								</div>
							</div>
						</div>
					</div>
					<!-- <div class="clear"></div> -->
					<div id="middle">
						<div id="middle_content" style="display: none;">
							<h4 id="notice" class="pre">当前位置：学院通知</h4>
							<nav id="nav_above">
								<div class="pre">
									<a href="javascript:;" class="pre_page" style="display: <?php echo $this->display;?>;">
										&lt;- Older posts </a>
								</div>
								<div class="pre">
									<a href="javascript:;" class="next_page" style="display: none;">
										Newer posts -&gt; </a>
								</div>
							</nav>

							<?php
							
                                for($i = 0; $i < count ( $this->news ); $i ++) {
								$temp = $this->news [$i];
								$article = "article-" . $temp ['id'] . ".html";
								?>
									<article id="arti" class='articles'>
									<h2>
										<a href="<?php echo $article; ?>"
											style="color: #000; text-decoration: none;"><?php echo $temp['title'];?> </a>
									</h2>
									<section style="word-wrap: break-word;"><?php echo $temp['content'];?></section>
	
									<div class="pre" style="margin-top: 10px;">
										<a href="<?php echo $article.'#comment'?>"
											style="color: hsl(206, 79%, 46%);"> <span>评论(<?php echo $temp['commNum'];?>)</span>
										</a>
									</div>
								</article>
							<?php } ?>
							
							<nav id="nav_below" style="margin-top: 30px;">
								<div class="pre">
									<a href="javascript:;" class="pre_page"> &lt;- Older posts </a>
								</div>
								<div class="pre">
									<a href="javascript:;" class="next_page" style="display: none;">
										Newer posts -&gt; </a>
								</div>
							</nav>
						</div>
						
						<!-- 教学部分 -->
						<div id="educate" class="pre" style="display: none;">
						    <h4>当前位置：教学</h4>
						    <form method="post" action="/main/addorupdateedu">
						    <nav class="nav_above" style="margin-top: 20px;">
						       <ul>
						       <?php 
						           $educatetype = $this->educatetype;
						           $educatecontent = $this->educatecontent;
						           $educatebody = $this->educatebody;
						           $tempname = null;
						           $tempid = null;
						           $length = null;
						           $body = null;
						           $tempcontent = null;
						           if(isset($educatetype)){
                                       foreach ($educatetype as $type) {
                                           $tempname = $type['showtype'];
                                           $tempid = $type['id'];
                                           if($tempname === 'text') {
						       ?>
									          <li>
									             <img src="./image/pngli.png" />
									             <div><?php echo $type['name']; ?>     <?php echo $type['comment']; ?>：</div>
									             <?php if(isset($educatebody)) { 
									                      for ($i = 0, $length = count($educatebody); $i < $length; $i++) {
                                                             $body = $educatebody[$i];
                                                             if($body['hasparent'] === '0' && $body['content_id'] === $tempid) {
									             ?>
									             			<input type="text" name="edutext[]" class="text-style" style="margin-top: 0px;" value="<?php echo $body['content']; ?>"/>
									             			<input type="text" name="textaction[]" style="display: none" value="up_dele <?php echo $tempid; ?>" />
									             <?php      break; 
                                                          } } 
									                        if($i >= $length) { ?>
									                            <input type="text" name="edutext[]" class="text-style" style="margin-top: 0px;"/>
									                            <input type="text" name="textaction[]" style="display: none" value="add <?php echo $tempid; ?>" />
									             <?php
									                     } } else { 
                                                 ?>
                                                           <input type="text" name="edutext[]" class="text-style" style="margin-top: 0px;"/>
                                                           <input type="text" name="textaction[]" style="display: none" value="add <?php echo $tempid; ?>" />
                                                 <?php   }?>
									          </li>
							   <?php      } else if($tempname === 'select') {?>
									          <li>
									             <img src="./image/pngli.png" />
									             <div><?php echo $type['name']; ?>：</div>
									             <select name="educatese[]" style="margin-left: 20px;">
									               <?php foreach ($educatecontent as $content) {
									                         $tempcontent = $content['content'];
									                         if($content['type_id'] === $tempid) {
                                                              if(isset($educatebody)){
	                                                             for ($i = 0, $length = count($educatebody); $i < $length; $i++) {   
										                          $body = $educatebody[$i];
										                           if($body['hasparent'] === '1' && $body['content_id'] === $content['id']) {
	                                                   ?>
										                          <option selected="selected"><?php echo $tempcontent; ?></option>
										               <?php
										                           break; 
	                                                            } }
	                                                              if($i >= $length){
	                                                   ?>
	                                                               <option><?php echo $tempcontent; ?></option>
                                                   <?php 
                                                            } } else { 
                                                   ?>
                                                             <option><?php echo $tempcontent; ?></option> 
                                                   <?php } } } ?>
									             </select>
									          </li>
						       <?php     } else {?>
									          <li>
									             <img src="./image/pngli.png" />
									             <div><?php echo $type['name']; ?></div>
									             <?php if(isset($educatecontent)) { 
									                        foreach ($educatecontent as $content){
                                                               $tempcontent = $content['content'];
                                                               if($content['type_id'] === $tempid) {
                                                               // 判断是否之前有用户填写
                                                               if(isset($educatebody)){
                                                                 for($i = 0, $length = count($educatebody); $i < $length; $i++) {
                                                                    $body = $educatebody[$i];
                                                                    if($body['hasparent'] === '1' && $body['content_id'] === $content['id']) {
									             ?>
															             <div style="float: none;clear: both;">
															                   <input name="eduelse[]" type="<?php echo $tempname;?>" value="<?php echo $tempcontent; ?>" checked="checked"/>
															                   <?php echo $tempcontent; ?>
															             </div>
									             <?php 
                                                                    break;
                                                  } }
                                                                    if($i >= $length) {
                                                  ?> 
                                                                          <div style="float: none;clear: both;">
															                   <input name="eduelse[]" type="<?php echo $tempname;?>" value="<?php echo $tempcontent; ?>" />
															                   <?php echo $tempcontent; ?>
															             </div>   
                                                  <?php } } else {?>
                                                                       <div style="float: none;clear: both;">
															                   <input name="eduelse[]" type="<?php echo $tempname;?>" value="<?php echo $tempcontent; ?>" />
															                   <?php echo $tempcontent; ?>
															             </div>
                                                  <?php } } } }?>
									          </li>
						       <?php    } } } ?>
						                      <li>
						                         <input style="display: none;" name="user" value="<?php echo $this->user['id']; ?>" />
						                         <input type="submit" class="edu_save" value="提交"/>
						                         <input type="reset" class="edu_cancel" value="取消" />
						                      </li>
						       </ul>
						    </nav>
						     </form>
						</div>
						
						<!-- 科研部分 -->
						<div id="teach" class="pre" style="display: none;">
						   <h4 id="notice">当前位置：科研</h4>
						   <?php
						      // 从数据库取出数据 
						      $teachtype = $this->teachtype;
						      $teachcontent = $this->teachcontent;
						      $teachsubcontent = $this->teachsubcontent;
						      $teachbody = $this->teachbody;
						      if(isset($teachtype)){
                                 foreach ($teachtype as $num => $name){
						    ?>
							   <nav class="nav_above" style="margin-top: 20px;">
							      <div style="font-weight: bold;"><?php echo $name['name']; ?></div>
							      <?php 
							          $itcontent = isset($teachcontent[$num]) ? $teachcontent[$num] : null;
							          if($itcontent) { 
                                      foreach ($itcontent as $contentnum => $contentvalue){
                                  ?>
								      <div style="background-color: hsl(0, 0%, 96%);padding-top: 5px; padding-bottom: 10px;">
								      
									      <div style="padding-left: 10px;font-weight: bold;margin-top: 10px;"><?php echo $contentvalue['name']; ?></div>
									      <?php if($contentvalue['haschildren'] === '1') { 
									            foreach ($teachsubcontent as $subcontentnum => $subcontentvalue) {
                                                  if ($subcontentvalue['parent'] == $contentnum && $subcontentvalue['root'] == $num){
									      ?>
										      <div class="teach_mar" style="padding-left: 20px;font-weight: bold;"><?php echo $subcontentvalue['name']; ?></div>
										      <?php if(isset($teachbody)) {
										            foreach ($teachbody as $bodyvalue) {
                                                      if($bodyvalue['hassubparent'] == 1 && $bodyvalue['content_id'] === $subcontentvalue['id']){
										      ?>
											      <div class="teach_mar teach_edit" style="padding-left: 20px;"><?php echo $bodyvalue['name']; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;排名:<?php echo $bodyvalue['condition']; ?><a href="javascript:;" class="edit">编辑</a>
											      <div style="display: none;"><?php echo $bodyvalue['id'];?></div>
											      </div>
											  <?php } } }?>
											  <div style="display: none;">1</div>
											  <div style="display: none; "><?php echo $subcontentvalue['id']; ?></div>
											  <div style="display: none; "><?php echo $this->user['id']; ?></div>
											  <div class="teach_add teach_mar" style="padding-left: 20px;">添加</div>
											  
									       <?php } } } else {
									       	      if(isset($teachbody)) {
										            foreach ($teachbody as $bodyvalue) {
                                                      if($bodyvalue['hassubparent'] == 0 && $bodyvalue['content_id'] === $contentvalue['id']){
                                            ?>
											      <div class="teach_mar teach_edit" style="padding-left: 20px;"><?php echo $bodyvalue['name']; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;排名:<?php echo $bodyvalue['condition']; ?><a href="javascript:;" class="edit">编辑</a>
											      <div style="display: none;"><?php echo $bodyvalue['id'];?></div>
											      </div>
											  <?php } } }?>
											  <div style="display: none;">0</div>
											  <div style="display: none; "><?php echo $contentvalue['id']; ?></div>
											  <div style="display: none; "><?php echo $this->user['id']; ?></div>
											  <div class="teach_add teach_mar" style="padding-left: 20px;">添加</div>
									      <?php }?>
								      </div>
								      <?php }
                                  } ?>
							      <div style="border-bottom: 2px dashed black; margin-top: 10px;"></div>
							   </nav>
						   <?php 
						        }
						      }
						   ?>
						</div>
						
						<!-- 技术推广部分 -->
						<div id="teachnology" style="display: none;" class="pre" >
						    <h4 id="notice">当前位置：技术推广</h4>
						    <?php 
						       $teachnotype = $this->teachnotype;
						       $teachnocontent = $this->teachnocontent;
						       $teachnobody = $this->teachnobody;
						       if (isset($teachnotype)) {
                                   foreach ($teachnotype as $num => $name){
						    ?>
						    <nav class="nav_above" style="margin-top: 20px;">
							      <div style="font-weight: bold;"><?php echo $name['name']; ?></div>
							<?php 
							       if (isset($teachnocontent)) {
                                      foreach ($teachnocontent as $contentid => $contentname) {
                                         if ($contentname['type_id'] == $name['id']) {
							?>
							      <div style="background-color: hsl(0, 0%, 96%);padding-top: 5px; padding-bottom: 10px;">
								       <div style="padding-left: 10px;font-weight: bold;margin-top: 10px;"><?php echo $contentname['name']; ?></div>
						    <?php 
						             if (isset($teachnobody)) {
                                        foreach ($teachnobody as $bodyid => $bodyname) {
                                            if ($bodyname['content_id'] == $contentname['id']) {
						   ?>
						     <div class="teachno_mar teach_edit" style="padding-left: 20px;"><?php echo $bodyname['name']; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;排名:<?php echo $bodyname['condition']; ?><a href="javascript:;" class="edit">编辑</a>      
						     <div style="display: none; "><?php echo $bodyname['id']; ?></div>
						     </div>
						   <?php } } } ?>
						        <div style="display: none; "><?php echo $contentname['id']; ?></div>
						        <div style="display: none; "><?php echo $this->user['id']; ?></div>
						        <div class="teach_add teachno_mar" style="padding-left: 20px;">添加</div>
						      </div>
						   <?php } } } ?>
						      </nav>
						   <?php } }?>
						</div>
						
						<!-- 数据生成部分 -->
						<div id="generation" style="display: none;"></div>
						
						<div id="addupdate" style="display: none;">
						   <ul>
						      <li>
						         <div>
						                                项目名称: 
						         </div>
						         <input type="text" id="projectname" value="" class="text-size text-style"/>
						      </li>
						      <li>
						         <div>
						                                     排名: 
						         </div>
						         <input type="text" id="projectrow" value="" class="text-size text-style"/>
						         <!-- 编辑，添加界面使用 -->
						         <div id="content_id" style="display: none;"></div>
						         <!-- 添加界面使用 -->
						         <div id="hassubchildren" style="display: none; "></div>
						         <div id="userid" style="display: none;"></div>
						      </li>
						      <li>
						         <input type="button" class="save-type" value="保存" style="height: 40px;margin-top: 30px;"/>
						         <input type="button" class="cancel-type" value="取消" style="height: 40px;margin-top: 30px;"/>
						      </li>
						   </ul>
						</div>
					</div>
					<div id="right">
						<!-- 插件列表-->
						<div id="plugs">
							<div id="datepicker"></div>
						</div>
						<ul>
							<li>
								<h3>友情链接</h3>
							</li>
							    <?php
											
                                  for($i = 0; $i < count ( $this->links ); $i ++) {
												$temp = $this->links [$i];
												?>
								    <li class="pre"><a href="<?php echo $temp['url']; ?>"
								target="_blank"><span><?php echo $temp['name']; ?></span></a></li>
								<?php } ?>
							</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- 结尾部分-->
	<footer style="margin-top: 25px;">
		<div>SCAU Copyright © 2011华南农业大学.All rights reserved.</div>
		<div>地址：广州市天河区五山华南农业大学</div>
		<div>
			联系人:林滨 微博：<a href="http://weibo.com/dashilin" target="__blank">http://weibo.com/dashilin</a>
		</div>
	</footer>

</body>

<script type="text/javascript" src="./js/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="./js/jquery-ui.js"></script>
<script type="text/javascript" src="./js/modules/init.js"></script>
<script type="text/javascript" src="./js/modules/indexMain.js"></script>
<script type="text/javascript" src="./js/animate.js"></script>
</html>
